### ISSUE TITLE
Linear Advance Factor decimals

### ISSUE THREAD

**Issue by Ex0ry** [fieldOfView/Cura-MaterialSettingsPlugin#1]
Hello, 
First i would like to express what of a relief your plugin brings. Its amazing! 
I never really understood, why flow settings etc. are not handled per material in cura. 

However i still got one Problem:
Since the Range of K-Factors changed in the Marlin Firmware, it is common to have very small Factors (like 0.7 for PLA), which require decimal places to be precise enough.
But when i add the LA Factor to the print settings Tab (under Materials), it is only possible to save whole Numbers.
Is it possible to change that?

Thanks in 'advance' ;-D

**Comment by DruckiMcDruck** [comment]
This is a bug in Cura itself and not in this plugin... Have a look at:
https://github.com/fieldOfView/Cura-LinearAdvanceSettingPlugin/issues/6#issuecomment-487364138

**Comment by fieldOfView** [comment]
This issue is the reason I have not yet published this plugin in the Marketplace. I'm still mulling over a workaround.

**Comment by fieldOfView** [comment]
I have found a way to patch this up from inside the plugin. A testing version is available here:
http://files.fieldofview.com/cura/MaterialSettingsPlugin-v6.0.0-2019-06-14T14_49_58Z.curapackage

**Comment by Ex0ry** [comment]
Not working for me on Cura 4.1.0...
I'm still unable to enter float values for the LA factor.
Integer Values also stopped working, meaning nothing is transferred over. (LA Factor under has no effect even with a blank standard profile)
Installation works just as before right?

**Comment by fieldOfView** [comment]
Thanks for testing. There are two issues at play here. First, there's a mistake in the MaterialSettingsPlugin which still did not allow you to enter decimals and which I fixed here: https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/commit/d3b723984d4c3338bc9c0ab9e3c666f1825c0962. 

The more involved issue that I am working on now is that the Linear Advance plugin does not support multiple extruders and as a consequence does not let you specify the Linear Advance Factor in the material in the first place (even for single extruder prints, because they are just seen as multi-extruder printers where the number of extruders is 1). So that plugin will need to be changed for this to work.

**Comment by fieldOfView** [comment]
New versions of both the MaterialSettingsPlugin and the ZOffset and LinearAdvance setting plugins have been submitted to the Marketplace.

**Comment by Ex0ry** [comment]
Does this take a few days until available? 
Unable to find MaterialSettings in the Marketplace...
Last Update of the LinearAdvance plugin is also a while back.

**Comment by fieldOfView** [comment]
Plugins submitted to the Marketplace are tested at Ultimaker. This takes a couple of days, depending on how busy the team is.

**Comment by fieldOfView** [comment]
The Material Settings plugin and fixed versions of the Linear Advance and Z Offset plugins are now available from the Marketplace.
