### ISSUE TITLE
Cannot add or duplicate filament

### ISSUE THREAD

**Issue by ladismrkolj** [fieldOfView/Cura-MaterialSettingsPlugin#9]
When the plugin is active the duplicate or create buttons in the materials pane does nothing. When the plugin is disabled it again works. I'm using Cura 4.4.1

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/issues/7, fixed in https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/commit/9ca0c6d0be2c7cf21ab7944d6163f04a9571dfe0

I have submitted a fixed version to the Marketplace, which will become available once it has been tested by Ultimaker.

Thanks for reporting.
